version: '3'

services:

  zalenium:
    image: dosel/zalenium:latest
    container_name: zalenium
    ports:
      - "4444:4444"
    restart: unless-stopped
    tty: true
    command: ["start", "--desiredContainers", "5", "--maxDockerSeleniumContainers", "10","--sauceLabsEnabled","false","--screenWidth", "1920", "--screenHeight", "1080"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/videos:/home/seluser/videos
    privileged: true
    networks:
      mynetwork:
        aliases:
          - chrome

  selenium-tests:
    image: selenium-test:latest
    container_name: selenium-test
    depends_on:
      - zalenium
    networks:
      mynetwork:
    volumes:
      - /tmp/test-results:/target
      - "${HOME}/.m2:/root/.m2"

networks:
  mynetwork:
    driver: bridge

